### ISSUE TITLE
Organize project code

### ISSUE THREAD

**Issue by perryprog** [GrafeasGroup/tor_app#1]
Add some more structure to tor_web

i.e. project modules, scripts, etc

**Comment by TheLonelyGhost** [comment]
@perryprog I'm not quite sure what the objective of this issue is. All I've gathered is that we need to reorganize the app somehow. Any more specificity? Are we trying to modularize it in some particular way? Is this a broad-strokes objective to figure out how we should organize the code so that it's reusable?

I guess I'm just looking for some acceptance criteria. If I'm understanding things correctly, what do you think about this?

> Determine a structure for tor_app such that adding additional target platforms (e.g., web browsers, electron) does not significantly change the underlying code.

We can gather that the objective is to keep the code modularized in a way that changing platform is easy and doesn't jeopardize the stability of the overall application.

**Comment by perryprog** [comment]
This is for my own API, since I moved it from my own repo to the directory `tor_web`.

You can ignore it.

Specifically, it was adding some more structure and the python modules, since it's a total mess right now.

**Comment by itsthejoker** [comment]
Since we're currently in the investigation stage, let's close this for now. We can reopen it / come back to it later if needed.
